services:
  - type: web
    name: khata-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: KHATA_MODE
        value: local
      - key: PYTHON_VERSION
        value: "3.11.6"
